[package]
name = "reproto-pack"
version = "0.3.39"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/reproto/reproto"
homepage = "https://github.com/reproto/reproto"
documentation = "https://docs.rs/reproto"
description = """
Utility application to pack subleme themes and syntaxes for reproto.
"""

[dependencies]
syntect = "2"
clap = "2"

[[bin]]
name = "reproto-pack"
path = "main.rs"
