[package]
name = "reproto-pack"
version = "0.4.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/reproto/reproto"
homepage = "https://github.com/reproto/reproto"
documentation = "https://docs.rs/reproto"
description = """
Utility application to pack subleme themes and syntaxes for reproto.
"""

[dependencies]
syntect = "4.2.0"
clap = "2.33.1"

[[bin]]
name = "reproto-pack"
path = "main.rs"
