[package]
name = "reproto-it"
version = "1.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"

[dependencies]
serde_json = "1.0.55"
serde = {version = "1.0.112", features = ["derive"]}
reqwest = {version = "0.10.6", features = ["json"]}
percent-encoding = "2.1.0"
chrono = {version = "0.4.11", features = ["serde"]}
url = "2.1.1"
