[package]
name = "rust"
version = "0.3.30"
authors = ["John-John Tedro <udoprog@tedro.se>"]

[dependencies]
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
reqwest = "0.8"
chrono = {version = "0.4", features = ["serde"]}
